# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('blog_matter', models.TextField(verbose_name='博客正文')),
                ('write_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
            },
        ),
        migrations.CreateModel(
            name='Blogs_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_type', models.CharField(max_length=30, verbose_name='博客类别')),
            ],
            options={
                'verbose_name': '博客类别表',
                'verbose_name_plural': '博客类别表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.Blogs_type', verbose_name='博客类别'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.User', verbose_name='用户名'),
        ),
    ]
